-- Crew sharing. One table: an accepted, unrevoked invite IS the pairing.
--
-- Generated by drizzle-kit, then trimmed: the generated file also re-emitted
--   ALTER TABLE flights ADD arrival_notified_at / arrival_alert_stage
--   ALTER TABLE notification_prefs ADD arrival_enabled
-- because 0010_add_arrival_notified_at.sql and 0011_arrival_alert_stages.sql were written by
-- hand and never got drizzle snapshots, so the snapshot drizzle diffed against predates them.
-- Those columns already exist in production; re-adding them fails with "duplicate column name".
CREATE TABLE `crew_invites` (
	`id` text PRIMARY KEY NOT NULL,
	`from_user_id` text NOT NULL,
	`to_email` text NOT NULL,
	`token` text NOT NULL,
	`created_at` integer NOT NULL,
	`accepted_at` integer,
	`accepted_by_user_id` text,
	`revoked_at` integer,
	FOREIGN KEY (`from_user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`accepted_by_user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `crew_invites_token_idx` ON `crew_invites` (`token`);--> statement-breakpoint
CREATE INDEX `crew_invites_from_user_idx` ON `crew_invites` (`from_user_id`);--> statement-breakpoint
CREATE INDEX `crew_invites_accepted_by_idx` ON `crew_invites` (`accepted_by_user_id`);--> statement-breakpoint
CREATE INDEX `crew_invites_to_email_idx` ON `crew_invites` (`to_email`);
--> statement-breakpoint
-- The app refuses a duplicate invite before inserting, but two requests can pass that check
-- concurrently. Partial, so a withdrawn invite doesn't block ever asking that person again.
CREATE UNIQUE INDEX `crew_invites_active_pair_idx` ON `crew_invites` (`from_user_id`, `to_email`) WHERE `revoked_at` IS NULL;
